import type { RandomEvent } from '@/types';

export const RANDOM_EVENTS: RandomEvent[] = [
  {
    id: 'viral_trend_bikes',
    nameKey: 'events.viral_trend_bikes.name',
    descKey: 'events.viral_trend_bikes.desc',
    emoji: '🔥',
    type: 'demand',
    weight: 3,
    predictable: true,
    productModifiers: { bikes: 1.45, escooters: 1.2 },
    locationModifiers: {},
    generalDemandModifier: 1.0,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'school_season',
    nameKey: 'events.school_season.name',
    descKey: 'events.school_season.desc',
    emoji: '📚',
    type: 'demand',
    weight: 4,
    predictable: true,
    productModifiers: { backpacks: 1.4, bottles: 1.2 },
    locationModifiers: { school: 1.35, university: 1.25 },
    generalDemandModifier: 1.0,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'sports_event',
    nameKey: 'events.sports_event.name',
    descKey: 'events.sports_event.desc',
    emoji: '🏆',
    type: 'demand',
    weight: 3,
    predictable: true,
    productModifiers: { headphones: 1.3, bottles: 1.35, bikes: 1.2 },
    locationModifiers: { sports: 1.5, tourist: 1.3 },
    generalDemandModifier: 1.0,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'new_competitor',
    nameKey: 'events.new_competitor.name',
    descKey: 'events.new_competitor.desc',
    emoji: '⚔️',
    type: 'market',
    weight: 4,
    predictable: true,
    productModifiers: {},
    locationModifiers: { mall: 0.78, university: 0.82, tourist: 0.80 },
    generalDemandModifier: 0.87,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'material_cost_spike',
    nameKey: 'events.material_cost_spike.name',
    descKey: 'events.material_cost_spike.desc',
    emoji: '📦',
    type: 'cost',
    weight: 4,
    predictable: true,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.0,
    costModifier: 1.28,
    investmentModifier: 1.0,
  },
  {
    id: 'good_reviews',
    nameKey: 'events.good_reviews.name',
    descKey: 'events.good_reviews.desc',
    emoji: '⭐',
    type: 'market',
    weight: 4,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.22,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'bad_reviews',
    nameKey: 'events.bad_reviews.name',
    descKey: 'events.bad_reviews.desc',
    emoji: '💢',
    type: 'market',
    weight: 3,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 0.75,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'eco_trend',
    nameKey: 'events.eco_trend.name',
    descKey: 'events.eco_trend.desc',
    emoji: '🌿',
    type: 'demand',
    weight: 3,
    predictable: true,
    productModifiers: { bikes: 1.3, escooters: 1.35, bottles: 1.25 },
    locationModifiers: {},
    generalDemandModifier: 1.0,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'economic_upswing',
    nameKey: 'events.economic_upswing.name',
    descKey: 'events.economic_upswing.desc',
    emoji: '📊',
    type: 'macro',
    weight: 3,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.15,
    costModifier: 1.0,
    investmentModifier: 1.25,
  },
  {
    id: 'mild_recession',
    nameKey: 'events.mild_recession.name',
    descKey: 'events.mild_recession.desc',
    emoji: '📉',
    type: 'macro',
    weight: 3,
    predictable: false,
    productModifiers: { escooters: 0.75, headphones: 0.82, skateboards: 0.88 },
    locationModifiers: {},
    generalDemandModifier: 0.82,
    costModifier: 1.0,
    investmentModifier: 0.70,
  },
  {
    id: 'viral_social_media',
    nameKey: 'events.viral_social_media.name',
    descKey: 'events.viral_social_media.desc',
    emoji: '📱',
    type: 'demand',
    weight: 3,
    predictable: true,
    productModifiers: { skateboards: 1.5, headphones: 1.4 },
    locationModifiers: { university: 1.3, school: 1.2 },
    generalDemandModifier: 1.0,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'supply_disruption',
    nameKey: 'events.supply_disruption.name',
    descKey: 'events.supply_disruption.desc',
    emoji: '🚫',
    type: 'operational',
    weight: 3,
    predictable: true,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.0,
    costModifier: 1.35,
    investmentModifier: 1.0,
  },
  {
    id: 'local_festival',
    nameKey: 'events.local_festival.name',
    descKey: 'events.local_festival.desc',
    emoji: '🎉',
    type: 'demand',
    weight: 3,
    predictable: true,
    productModifiers: {},
    locationModifiers: { tourist: 1.55, sports: 1.35, mall: 1.2 },
    generalDemandModifier: 1.1,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'tax_break',
    nameKey: 'events.tax_break.name',
    descKey: 'events.tax_break.desc',
    emoji: '🏛️',
    type: 'macro',
    weight: 2,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.08,
    costModifier: 0.88,
    investmentModifier: 1.1,
  },
  {
    id: 'energy_crisis',
    nameKey: 'events.energy_crisis.name',
    descKey: 'events.energy_crisis.desc',
    emoji: '⚡',
    type: 'operational',
    weight: 2,
    predictable: false,
    productModifiers: { escooters: 0.7 },
    locationModifiers: {},
    generalDemandModifier: 0.9,
    costModifier: 1.2,
    investmentModifier: 0.85,
  },
  {
    id: 'influencer_collab',
    nameKey: 'events.influencer_collab.name',
    descKey: 'events.influencer_collab.desc',
    emoji: '🌟',
    type: 'demand',
    weight: 2,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.28,
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'tech_regulation',
    nameKey: 'events.tech_regulation.name',
    descKey: 'events.tech_regulation.desc',
    emoji: '📋',
    type: 'operational',
    weight: 2,
    predictable: true,
    productModifiers: { escooters: 0.72 },
    locationModifiers: {},
    generalDemandModifier: 1.0,
    costModifier: 1.15,
    investmentModifier: 0.80,
  },
  {
    id: 'crypto_boom',
    nameKey: 'events.crypto_boom.name',
    descKey: 'events.crypto_boom.desc',
    emoji: '🚀',
    type: 'macro',
    weight: 2,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.0,
    costModifier: 1.0,
    investmentModifier: 2.5,   // applies to crypto/startup
  },
  {
    id: 'partnership_opportunity',
    nameKey: 'events.partnership_opportunity.name',
    descKey: 'events.partnership_opportunity.desc',
    emoji: '🤝',
    type: 'market',
    weight: 2,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 1.25,  // only if student has >$15k liquidity
    costModifier: 1.0,
    investmentModifier: 1.0,
  },
  {
    id: 'inflation_spike',
    nameKey: 'events.inflation_spike.name',
    descKey: 'events.inflation_spike.desc',
    emoji: '💸',
    type: 'macro',
    weight: 3,
    predictable: false,
    productModifiers: {},
    locationModifiers: {},
    generalDemandModifier: 0.88,
    costModifier: 1.18,
    investmentModifier: 0.9,
  },
];

export const TOTAL_EVENT_WEIGHT = RANDOM_EVENTS.reduce((s, e) => s + e.weight, 0);

export function pickRandomEvents(count: number = 1): RandomEvent[] {
  const selected: RandomEvent[] = [];
  const pool = [...RANDOM_EVENTS];

  for (let i = 0; i < count && pool.length > 0; i++) {
    const totalWeight = pool.reduce((s, e) => s + e.weight, 0);
    let rand = Math.random() * totalWeight;
    const idx = pool.findIndex(e => {
      rand -= e.weight;
      return rand <= 0;
    });
    if (idx >= 0) {
      selected.push(pool[idx]);
      pool.splice(idx, 1);
    }
  }
  return selected;
}
