import type { Location } from '@/types';

export const LOCATIONS: Record<string, Location> = {
  school: {
    id: 'school',
    nameKey: 'locations.school.name',
    descKey: 'locations.school.desc',
    emoji: '🏫',
    color: '#3b82f6',
    rentPerRound: 3500,
    trafficMultiplier: 0.9,
    segment: 'teens',
    competitionLevel: 0.4,
    growthPotential: 0.5,
    risk: 0.25,
  },
  university: {
    id: 'university',
    nameKey: 'locations.university.name',
    descKey: 'locations.university.desc',
    emoji: '🎓',
    color: '#6366f1',
    rentPerRound: 4500,
    trafficMultiplier: 1.1,
    segment: 'young_adults',
    competitionLevel: 0.55,
    growthPotential: 0.75,
    risk: 0.3,
  },
  mall: {
    id: 'mall',
    nameKey: 'locations.mall.name',
    descKey: 'locations.mall.desc',
    emoji: '🛍️',
    color: '#f59e0b',
    rentPerRound: 9000,
    trafficMultiplier: 1.5,
    segment: 'general',
    competitionLevel: 0.85,
    growthPotential: 0.6,
    risk: 0.45,
  },
  residential: {
    id: 'residential',
    nameKey: 'locations.residential.name',
    descKey: 'locations.residential.desc',
    emoji: '🏘️',
    color: '#10b981',
    rentPerRound: 2500,
    trafficMultiplier: 0.7,
    segment: 'families',
    competitionLevel: 0.3,
    growthPotential: 0.45,
    risk: 0.15,
  },
  tourist: {
    id: 'tourist',
    nameKey: 'locations.tourist.name',
    descKey: 'locations.tourist.desc',
    emoji: '🗺️',
    color: '#ec4899',
    rentPerRound: 7000,
    trafficMultiplier: 1.3,
    segment: 'tourists',
    competitionLevel: 0.65,
    growthPotential: 0.7,
    risk: 0.7,
  },
  sports: {
    id: 'sports',
    nameKey: 'locations.sports.name',
    descKey: 'locations.sports.desc',
    emoji: '⚽',
    color: '#14b8a6',
    rentPerRound: 4000,
    trafficMultiplier: 1.0,
    segment: 'athletes',
    competitionLevel: 0.5,
    growthPotential: 0.55,
    risk: 0.35,
  },
};

export const LOCATION_LIST = Object.values(LOCATIONS);
